{
    "id": 183739,
    "name": "CVE-2021-33010",
    "cwe": "NVD-CWE-Other",
    "modified": "2022-04-13T11:45:47",
    "published": "2022-04-04T18:15:09",
    "status": "Analyzed",
    "summary": "An exception is thrown from a function in AVEVA System Platform versions 2017 through 2020 R2 P01, but it is not caught, which may cause a denial-of-service condition.",
    "cvss3": {
        "cvss": 7.5,
        "exploitability_score": 3.9,
        "impact_score": 3.6,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "cvss2": {
        "exploitability_score": 10.0,
        "impact_score": 2.9,
        "cvss": 5.0,
        "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
    },
    "cpes": [
        {
            "id": 863478
        },
        {
            "id": 863479
        },
        {
            "id": 863480
        },
        {
            "id": 863481
        }
    ]
}