{
    "id": 44057,
    "name": "CVE-2009-5010",
    "cwe": "CWE-362",
    "modified": "2010-10-20T02:00:00",
    "published": "2010-10-19T18:00:02",
    "status": "Analyzed",
    "summary": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.1 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, a different vulnerability than CVE-2010-3494.",
    "cvss3": null,
    "cvss2": null,
    "cpes": []
}