{
    "id": 256537,
    "name": "CVE-2024-39614",
    "cwe": "Unknown",
    "modified": "2024-07-11T11:05:54",
    "published": "2024-07-10T03:15:12",
    "status": "Awaiting Analysis",
    "summary": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters.",
    "cvss3": null,
    "cvss2": null,
    "cpes": []
}