{
    "id": 195713,
    "name": "CVE-2022-35937",
    "cwe": "CWE-125",
    "modified": "2022-09-20T14:33:28",
    "published": "2022-09-16T18:15:10",
    "status": "Analyzed",
    "summary": "TensorFlow is an open source platform for machine learning. The `GatherNd` function takes arguments that determine the sizes of inputs and outputs. If the inputs given are greater than or equal to the sizes of the outputs, an out-of-bounds memory read is triggered. This issue has been patched in GitHub commit 595a65a3e224a0362d7e68c2213acfc2b499a196. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
    "cvss3": {
        "cvss": 9.1,
        "exploitability_score": 3.9,
        "impact_score": 5.2,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H"
    },
    "cvss2": null,
    "cpes": [
        {
            "id": 806778
        },
        {
            "id": 806779
        },
        {
            "id": 834890
        },
        {
            "id": 834891
        },
        {
            "id": 834892
        },
        {
            "id": 834895
        },
        {
            "id": 834896
        },
        {
            "id": 889170
        },
        {
            "id": 889171
        },
        {
            "id": 889298
        },
        {
            "id": 889299
        },
        {
            "id": 889993
        },
        {
            "id": 889994
        },
        {
            "id": 933949
        },
        {
            "id": 933950
        },
        {
            "id": 933951
        },
        {
            "id": 933952
        }
    ]
}