{
    "id": 106958,
    "name": "CVE-2018-11499",
    "cwe": "CWE-416",
    "modified": "2019-07-23T16:15:11",
    "published": "2018-05-26T18:29:00",
    "status": "Modified",
    "summary": "A use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact.",
    "cvss3": null,
    "cvss2": null,
    "cpes": [
        {
            "id": 168598
        },
        {
            "id": 168599
        },
        {
            "id": 168600
        },
        {
            "id": 168601
        },
        {
            "id": 168602
        },
        {
            "id": 168603
        },
        {
            "id": 168604
        },
        {
            "id": 168605
        },
        {
            "id": 168606
        },
        {
            "id": 168607
        },
        {
            "id": 168608
        },
        {
            "id": 168609
        },
        {
            "id": 168610
        },
        {
            "id": 168611
        },
        {
            "id": 168612
        },
        {
            "id": 251444
        },
        {
            "id": 251445
        },
        {
            "id": 251446
        },
        {
            "id": 251447
        },
        {
            "id": 251448
        },
        {
            "id": 251449
        },
        {
            "id": 251450
        },
        {
            "id": 251451
        }
    ]
}