{
    "id": 93778,
    "name": "CVE-2015-3206",
    "cwe": "CWE-287",
    "modified": "2018-12-20T17:11:58",
    "published": "2017-08-25T16:29:00",
    "status": "Analyzed",
    "summary": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack.",
    "cvss3": null,
    "cvss2": null,
    "cpes": [
        {
            "id": 197953
        }
    ]
}