{
    "id": 44066,
    "name": "CVE-2010-3495",
    "cwe": "CWE-362",
    "modified": "2011-01-22T05:43:28",
    "published": "2010-10-19T18:00:04",
    "status": "Modified",
    "summary": "Race condition in ZEO/StorageServer.py in Zope Object Database (ZODB) before 3.10.0 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492.",
    "cvss3": null,
    "cvss2": null,
    "cpes": []
}