{
    "id": 159488,
    "name": "CVE-2021-28363",
    "cwe": "CWE-295",
    "modified": "2024-06-21T17:15:17",
    "published": "2021-03-15T17:15:19",
    "status": "Modified",
    "summary": "The urllib3 library 1.26.x before 1.26.4 for Python omits SSL certificate validation in some cases involving HTTPS to HTTPS proxies. The initial connection to the HTTPS proxy (if an SSLContext isn't given via proxy_config) doesn't verify the hostname of the certificate. This means certificates for different servers that still validate properly with the default urllib3 SSLContext will be silently accepted.",
    "cvss3": {
        "cvss": 6.5,
        "exploitability_score": 3.9,
        "impact_score": 2.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N"
    },
    "cvss2": {
        "exploitability_score": 10.0,
        "impact_score": 4.9,
        "cvss": 6.4,
        "vector": "AV:N/AC:L/Au:N/C:P/I:P/A:N"
    },
    "cpes": [
        {
            "id": 622632
        },
        {
            "id": 677468
        },
        {
            "id": 677472
        },
        {
            "id": 677473
        },
        {
            "id": 677474
        },
        {
            "id": 749908
        }
    ]
}