{
    "id": 223288,
    "name": "CVE-2023-41105",
    "cwe": "CWE-426",
    "modified": "2023-11-07T03:20:53",
    "published": "2023-08-23T05:15:08",
    "status": "Modified",
    "summary": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
    "cvss3": {
        "cvss": 7.5,
        "exploitability_score": 3.9,
        "impact_score": 3.6,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
    },
    "cvss2": null,
    "cpes": [
        {
            "id": 454088
        },
        {
            "id": 852544
        },
        {
            "id": 852545
        },
        {
            "id": 852546
        },
        {
            "id": 852547
        },
        {
            "id": 852548
        },
        {
            "id": 852549
        },
        {
            "id": 887290
        },
        {
            "id": 887291
        },
        {
            "id": 934801
        },
        {
            "id": 934802
        },
        {
            "id": 934803
        },
        {
            "id": 934804
        },
        {
            "id": 934805
        },
        {
            "id": 969254
        },
        {
            "id": 969273
        },
        {
            "id": 1038912
        },
        {
            "id": 1038913
        },
        {
            "id": 1104577
        },
        {
            "id": 1104578
        }
    ]
}