{
    "id": 185890,
    "name": "CVE-2022-30284",
    "cwe": "CWE-88",
    "modified": "2024-06-10T17:15:52",
    "published": "2022-05-04T20:15:11",
    "status": "Modified",
    "summary": "In the python-libnmap package through 0.7.2 for Python, remote command execution can occur (if used in a client application that does not validate arguments). NOTE: the vendor believes it would be unrealistic for an application to call NmapProcess with arguments taken from input data that arrived over an untrusted network, and thus the CVSS score corresponds to an unrealistic use case. None of the NmapProcess documentation implies that this is an expected use case",
    "cvss3": {
        "cvss": 9.8,
        "exploitability_score": 3.9,
        "impact_score": 5.9,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    },
    "cvss2": {
        "exploitability_score": 10.0,
        "impact_score": 6.4,
        "cvss": 7.5,
        "vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
    },
    "cpes": [
        {
            "id": 873883
        },
        {
            "id": 873884
        },
        {
            "id": 873885
        },
        {
            "id": 873886
        },
        {
            "id": 873887
        },
        {
            "id": 873888
        },
        {
            "id": 873889
        },
        {
            "id": 873890
        },
        {
            "id": 873891
        },
        {
            "id": 873892
        },
        {
            "id": 873893
        },
        {
            "id": 873894
        },
        {
            "id": 873895
        },
        {
            "id": 873896
        },
        {
            "id": 873897
        },
        {
            "id": 873898
        },
        {
            "id": 873899
        },
        {
            "id": 873900
        },
        {
            "id": 873901
        },
        {
            "id": 873902
        }
    ]
}