{
    "id": 134029,
    "name": "CVE-2019-19275",
    "cwe": "CWE-125",
    "modified": "2023-11-07T02:07:37",
    "published": "2019-11-26T14:15:12",
    "status": "Modified",
    "summary": "typed_ast 1.3.0 and 1.3.1 has an ast_for_arguments out-of-bounds read. An attacker with the ability to cause a Python interpreter to parse Python source (but not necessarily execute it) may be able to crash the interpreter process. This could be a concern, for example, in a web-based service that parses (but does not execute) Python code. (This issue also affected certain Python 3.8.0-alpha prereleases.)",
    "cvss3": {
        "cvss": 7.5,
        "exploitability_score": 3.9,
        "impact_score": 3.6,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "cvss2": {
        "exploitability_score": 10.0,
        "impact_score": 2.9,
        "cvss": 5.0,
        "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
    },
    "cpes": [
        {
            "id": 450091
        },
        {
            "id": 450092
        }
    ]
}